Repository angular/angularfire, pull requests merged in 2021-09, with the labels that each got.

#2831 Updated id to $id
  src/schematics/deploy/schema.json
Labels: cla: yes, bump: major

#2917 Update getting-started.md: `/compat` missing from firebase import
  docs/auth/getting-started.md
Labels: cla: yes

#2920 Spicemix master #2813
  src/compat/performance/performance.service.ts
  src/compat/performance/performance.ts
Labels: cla: yes

#2922 chore(): Fix build in windows and test build/node in different OSes
  .github/workflows/test.yml
  package.json
  src/schematics/deploy/actions.jasmine.ts
  src/schematics/ng-add.jasmine.ts
  tools/build.ts
  yarn.lock
Labels: cla: yes

#2923 fix(compat/database): Zone should be destabilized on get
  src/compat/firestore/collection-group/collection-group.ts
  src/compat/firestore/collection/collection.ts
  src/compat/firestore/document/document.ts
Labels: cla: yes, bump: patch

#2927 fix(schematics): ng upgrade when e2e is present, fixes #2924
  src/schematics/update/v7/index.ts
Labels: cla: yes, bump: patch

#2928 chore(release): Release 7.0.4
  CHANGELOG.md
  package.json
Labels: cla: yes

#2938 Moving all samples to emulators, simplifying
  README.md
  samples/.emulator/.firebaserc
  samples/.emulator/database.rules.json
  samples/.emulator/firebase.json
  samples/.emulator/firestore.indexes.json
  samples/.emulator/firestore.rules
  samples/.emulator/functions/.eslintrc.js
  samples/.emulator/functions/.gitignore
  samples/.emulator/functions/package.json
  samples/.emulator/functions/src/index.ts
  samples/.emulator/functions/tsconfig.json
  samples/.emulator/functions/yarn.lock
  samples/.emulator/seed/auth_export/accounts.json
  samples/.emulator/seed/auth_export/config.json
  samples/.emulator/seed/database_export/aftest-94085.json
  samples/.emulator/seed/firebase-export-metadata.json
  samples/.emulator/seed/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  samples/.emulator/seed/firestore_export/all_namespaces/all_kinds/output-0
  samples/.emulator/seed/firestore_export/firestore_export.overall_export_metadata
  samples/.emulator/seed/storage_export/blobs/aftest-94085.appspot.com/google-g.png
  samples/.emulator/seed/storage_export/buckets.json
  samples/.emulator/seed/storage_export/metadata/aftest-94085.appspot.com/google-g.png.json
  samples/.emulator/storage.rules
  samples/advanced/package.json
  samples/advanced/src/environments/environment.ts
  samples/compat/angular.json
  samples/compat/functions/src/index.ts
  samples/compat/package.json
  samples/compat/src/app/app.module.ts
  samples/compat/src/app/app.server.module.ts
  samples/compat/src/app/auth/auth.component.ts
  samples/compat/src/app/database/database.component.ts
  samples/compat/src/app/firestore-offline/firestore-offline.component.spec.ts
  samples/compat/src/app/firestore-offline/firestore-offline.component.ts
  samples/compat/src/app/firestore-offline/firestore-offline.module.ts
  samples/compat/src/app/firestore/firestore.component.ts
  samples/compat/src/app/functions/functions.component.ts
  samples/compat/src/app/home/home.component.ts
  samples/compat/src/app/protected-lazy/protected-lazy.component.ts
  samples/compat/src/app/storage/storage.component.ts
  samples/compat/src/app/upboats/upboats.component.ts
  samples/compat/src/environments/environment.emulated.ts
  samples/compat/src/environments/environment.ts
  samples/compat/yarn.lock
  samples/modular/.firebaserc
  samples/modular/firebase.json
  samples/modular/package.json
  samples/modular/src/app/app.browser.module.ts
  samples/modular/src/app/app.server.module.ts
  samples/modular/src/app/database/database.component.ts
  samples/modular/src/app/firestore/firestore.component.ts
  samples/modular/src/app/storage/storage.component.ts
  samples/modular/src/app/upboats/upboats.component.ts
  samples/modular/src/environments/environment.ts
Labels: cla: yes

#2939 Update deps, fixes compat issues #2932
  samples/advanced/yarn.lock
  samples/compat/package.json
  samples/compat/yarn.lock
  samples/modular/package.json
  samples/modular/yarn.lock
  yarn.lock
Labels: cla: yes

#2940 App check
  package.json
  samples/advanced/server.ts
  samples/advanced/src/app/app-check/app-check.component.spec.ts
  samples/advanced/src/app/app-check/app-check.component.ts
  samples/advanced/src/app/app.module.ts
  samples/advanced/src/app/auth/auth.component.ts
  samples/advanced/src/app/database/database.component.ts
  samples/advanced/src/app/firestore/firestore.component.ts
  samples/advanced/src/app/functions/functions.component.ts
  samples/advanced/src/app/home/home.component.ts
  samples/advanced/src/app/messaging/messaging.component.ts
  samples/advanced/src/app/remote-config/remote-config.component.ts
  samples/advanced/src/environments/environment.prod.ts
  samples/advanced/src/environments/environment.ts
  samples/compat/src/app/app.module.ts
  samples/compat/src/environments/environment.prod.ts
  samples/compat/src/environments/environment.ts
  samples/modular/src/app/app-check/app-check.component.spec.ts
  samples/modular/src/app/app-check/app-check.component.ts
  samples/modular/src/app/app.module.ts
  samples/modular/src/app/auth/auth.component.ts
  samples/modular/src/app/database/database.component.ts
  samples/modular/src/app/firestore/firestore.component.ts
  samples/modular/src/app/functions/functions.component.ts
  samples/modular/src/app/home/home.component.ts
  samples/modular/src/app/messaging/messaging.component.ts
  samples/modular/src/app/remote-config/remote-config.component.ts
  samples/modular/src/environments/environment.prod.ts
  samples/modular/src/environments/environment.ts
  src/app-check/app-check.module.ts
  src/app-check/app-check.ts
  src/app-check/firebase.ts
  src/app-check/package.json
  src/app-check/public_api.ts
  src/auth/auth.module.ts
  src/compat/auth/auth.ts
  src/compat/database/database.spec.ts
  src/compat/database/database.ts
  src/compat/firestore/firestore.ts
  src/compat/functions/functions.ts
  src/compat/storage/storage.ts
  src/core.ts
  src/database/database.module.ts
  src/firestore/firestore.module.ts
  src/functions/functions.module.ts
  src/storage/storage.module.ts
  tools/build.ts
  tsconfig.base.json
Labels: cla: yes

#2930 fix typos
  docs/version-7-upgrade.md
Labels: cla: yes

#2921 Minor additions
  src/compat/performance/performance.service.ts
  src/compat/performance/performance.ts
  src/compat/storage/pipes/storageUrl.pipe.ts
  src/compat/storage/ref.ts
Labels: cla: yes, bump: minor

#2836 Schematics, schematics, schematics!
  .github/workflows/test.yml
  package.json
  samples/advanced/.firebaserc
  samples/advanced/angular.json
  samples/advanced/firebase.json
  samples/advanced/package.json
  samples/advanced/yarn.lock
  samples/modular/yarn.lock
  src/package.json
  src/schematics/add/index.ts
  src/schematics/add/schema.json
  src/schematics/collection.json
  src/schematics/common.ts
  src/schematics/deploy/actions.jasmine.ts
  src/schematics/deploy/actions.ts
  src/schematics/deploy/builder.ts
  src/schematics/deploy/functions-templates.ts
  src/schematics/deploy/schema.json
  src/schematics/firebaseTools.ts
  src/schematics/interfaces.ts
  src/schematics/migration.json
  src/schematics/ng-add-ssr.ts
  src/schematics/ng-add.jasmine.ts
  src/schematics/ng-add.ts
  src/schematics/ngcc-config.ts
  src/schematics/public_api.ts
  src/schematics/setup/index.ts
  src/schematics/setup/prompts.ts
  src/schematics/setup/schema.json
  src/schematics/setup/ssr.ts
  src/schematics/setup/static.ts
  src/schematics/tsconfig.json
  src/schematics/update/index.ts
  src/schematics/update/v7/index.ts
  src/schematics/utils.ts
  src/schematics/versions.json
  tools/build.ts
  yarn.lock
Labels: cla: yes, bump: minor

#2952 Missing deps, fixed ng add bug
  package.json
  src/package.json
  src/schematics/add/index.ts
  src/schematics/common.ts
  src/schematics/setup/prompts.ts
  src/schematics/setup/ssr.ts
  src/schematics/setup/static.ts
  src/schematics/utils.ts
  yarn.lock
Labels: cla: yes

#2954 7.1.0-rc.1 fixes
  src/package.json
  src/schematics/deploy/actions.jasmine.ts
  src/schematics/deploy/actions.ts
  src/schematics/interfaces.ts
  src/schematics/setup/index.ts
  src/schematics/setup/ssr.ts
  src/schematics/utils.ts
  src/schematics/versions.json
Labels: cla: yes

#2958 Adding multi-user support.
  src/schematics/deploy/actions.jasmine.ts
  src/schematics/deploy/actions.ts
  src/schematics/interfaces.ts
  src/schematics/setup/index.ts
  src/schematics/setup/prompts.ts
Labels: cla: yes

#2726 feat(deploy): target support for multi-site deploy options
  docs/deploy/getting-started.md
  src/schematics/deploy/actions.ts
  src/schematics/deploy/schema.json
  src/schematics/interfaces.ts
Labels: cla: yes, bump: minor

#2960 Adding storage list
  src/compat/storage/interfaces.ts
  src/compat/storage/ref.ts
Labels: cla: yes

#2961 Various improvements
  samples/advanced/angular.json
  samples/advanced/package.json
  samples/advanced/src/app/app.browser.module.ts
  samples/advanced/src/app/app.server.module.ts
  samples/advanced/src/app/database/lazyDatabase.ts
  samples/advanced/src/app/emulators.prod.ts
  samples/advanced/src/app/emulators.ts
  samples/advanced/src/app/functions/lazyFunctions.ts
  samples/advanced/src/app/getFirestore.ts
  samples/advanced/src/app/storage/lazyStorage.ts
  samples/advanced/yarn.lock
  src/core.ts
  src/schematics/deploy/actions.ts
  src/schematics/ng-add.jasmine.ts
  src/schematics/setup/ssr.ts
  src/schematics/setup/static.ts
Labels: cla: yes
